# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219ebb610289158c08116c399455b8abe86c955b17bd517cc95eda5cb13188fdcaa44b9217e816fa38aeee142d511af51d8d82db226792746093a9b57e14aece

test:
  secret_key_base: 1426206e2b3b78225bab9f7fffc821bdca9322ce895cb0edddafa922c4fb66f531f92c232848952903c29a234c095f7dee2bdc1c88a107c14295ffaa8bcef3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
